// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmuoctyoldoeemavuuhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtdW9jdHlvbGRvZWVtYXZ1dWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTkwNzQsImV4cCI6MjA2MTA5NTA3NH0.Fo9mSPUwnRosIVwkx8AJ1wI7kgJO4C6SAy2n0o9hVKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);